[project]
name = "asl-interpreter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "mediapipe==0.10.14",
    "numpy<2.0.0",
    "opencv-python==4.10.0.84",
    "setuptools>=82.0.0",
]
